### ISSUE TITLE
Error when unicode in file path

### ISSUE THREAD

**Issue by nausikaa-dot** [kz26/dottorrent#9]
Probably a duplicate of #3.

I've confirmed this only happens when the ä character is in the filename:
```
Traceback (most recent call last):
  File "/path/to/.local/bin/dottorrent", line 8, in <module>
    sys.exit(main())
  File "/path/to/.local/lib/python3.5/site-packages/dtcli/cli.py", line 137, in main
    t.generate(callback=progress_callback)
  File "/path/to/.local/lib/python3.5/site-packages/dottorrent/__init__.py", line 301, in generate
    for y in x[0].split(os.sep)[len(path_sp):]]
  File "/path/to/.local/lib/python3.5/site-packages/dottorrent/__init__.py", line 301, in <listcomp>
    for y in x[0].split(os.sep)[len(path_sp):]]
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 11: surrogates not allowed
```

**Comment by nausikaa-dot** [comment]
In my case, this occurred when there were Unicode surrogate pairs in the filename on Linux. See [this stackoverflow answer](https://stackoverflow.com/a/27367173).
